# Generated by Django 5.2.1 on 2025-06-08 19:02

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='nom')),
                ('house_number', models.IntegerField(verbose_name='numero')),
                ('street', models.CharField(max_length=50, verbose_name='voie')),
                ('postcode', models.PositiveSmallIntegerField(verbose_name='code postal')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='FR', verbose_name='téléphone')),
                ('infos', models.TextField(blank=True, max_length=100, verbose_name='informations supplémentaires')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
        ),
    ]
